export * from "./home";
//export * from "@/pages/rentalCatalgoue"
export * from "./tailoringCatalogue";
export * from "./rentalCatalogue";
export * from "./aboutUs";
export * from "./productDetails";
export * from "./cartPage";
export * from "./checkoutPage";
export * from "./loginPage";
export * from "./registerPage";
export * from "./yourOrdersPage";
export * from "./purchaseCatalogue";
