export * from "./home";
//export * from "@/pages/rentalCatalgoue"
export * from "./tailoringCatalogue";
export * from "./rentalCatalogue";
export * from "./aboutUs";
export * from "./rentalProductDetails";
export * from "./cartPage";
export * from "./checkoutPage";
export * from "./loginPage";
export * from "./registerPage";
export * from "./yourOrdersPage";
export * from "./purchaseCatalogue";
export * from "./orderManagement";
export * from "./orderManagementDetails";
export * from "./spinWheel";
export * from "./scratchCard";
export * from "./aboutUs";
export * from "./tailoringHome";
export * from "./contactUs";
export * from "./tailoringProductDetails";
export * from "./internal/businessPartnersRegistration";
export * from "./internal/rentalProductUploadForm";
export * from "./internal/adminDashboard";
export * from "./internal/tailoringProductUploadForm";
export * from "./services/MehendiArtistCard";
export * from "./services/MehendiArtistList";
export * from "./services/MehendiArtistDetail";
export * from "./services/ServiceUploadForm"
export * from "./services/serviceBookingPage"
export * from "./services/serviceHomePage"
export * from "./services/serviceDetailsPage"
export * from "./services/mehendiHomePage";
export * from "./internal/tailoringOrderManagement";
export * from "./internal/tailoringOrderManagementDetails";
export * from "./winner";
export * from "./razorPay";
export * from "./services/MehendiServiceBookingPage";
export * from "./services/serviceLandingPage";
export * from "./services/partnerSerivceManagementPage";
export * from "./services/servicePartnerLandingPage";
export * from "./services/partnerServiceBookingManagement";
export * from "./internal/mehendiOrderManagement";
export * from "./ProductManager";
export * from "./productManagerMain";
export * from "./productManagerWrapper";
